version: '3.8'

services:
  redmine:
    image: redmine:4.2
    user: redmine
    volumes:
      - /home/redmine/files:/usr/src/redmine/files
      - /home/redmine/redmine.db:/usr/src/redmine/sqlite/redmine.db
    # ports:
    #   - 3000:3000
    networks:
      - public-net
    configs:
      - source: config.yml
        target: /usr/src/redmine/config/configuration.yml
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        delay: 1s
        # order: stop-first
        failure_action: rollback
        monitor: 10s
      restart_policy:
        condition: on-failure
        delay: 1s
        max_attempts: 5
        window: 120s
      resources:
        limits:
          cpus: '0.5'
          memory: 1.5G
        reservations:
          cpus: '0.25'
          memory: 250M
      labels:
        # Enable Traefik for this service, to make it available in the public network
        - traefik.enable=true
        # Use the traefik-public network (declared below)
        - traefik.docker.network=traefik_public
        # Use the custom label "traefik.constraint-label=traefik-public"
        # This public Traefik will only use services with this label
        # That way you can add other internal Traefik instances per stack if needed
        - traefik.constraint-label=traefik-public
        # traefik-http set up only to use the middleware to redirect to https
        # Uses the environment variable DOMAIN
        - traefik.http.routers.redmine-http.rule=Host(`redmine.domain.com`)
        - traefik.http.routers.redmine-http.entrypoints=web
        - traefik.http.routers.redmine-http.middlewares=https-redirect
        # traefik-https the actual router using HTTPS
        # Uses the environment variable DOMAIN
        - traefik.http.routers.redmine-https.rule=Host(`redmine.domain.com`)
        - traefik.http.routers.redmine-https.entrypoints=websecure
        - traefik.http.routers.redmine-https.tls=true
        # Use the "le" (Let's Encrypt) resolver created below
        - traefik.http.routers.redmine-https.tls.certresolver=le
        # Define the port inside of the Docker service to use
        - traefik.http.services.redmine.loadbalancer.server.port=3000

configs:
  config.yml:
    name: 'redmine-config'
    external: true

networks:
  public-net:
    external: true
    name: traefik_public