{
 "title": "Docker Swarm",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Top vCPU usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "topk(5, tasks_cpu_usage)", "legendFormat": "{{prettyName}}" }
   ]
  },
  {
   "title": "VM CPU",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 13, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "nodes_cpu_percentage", "legendFormat": "{{nodeName}}" }
   ]
  },
  {
   "title": "Metric status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "conditions": [
      {
       "evaluator": {
        "params": [
         60000,
         0
        ],
        "type": "lt"
       },
       "operator": { "type": "and" },
       "query": { "params": [ "A" ] },
       "reducer": {
        "params": [],
        "type": "last"
       },
       "type": "query"
      }
     ],
     "type": "classic_conditions"
    }
   ]
  },
  {
   "title": "% Disk Usage",
   "type": "gauge",
   "gridPos": { "h": 11, "w": 3, "x": 21, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nodes_disk_percentage", "legendFormat": "{{nodeName}} ({{diskType}})" }
   ]
  },
  {
   "title": "Top RAM usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "topk(5, tasks_memory_usage)", "legendFormat": "{{prettyName}}" }
   ]
  },
  {
   "title": "VM Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 13, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "nodes_memory_percentage", "legendFormat": "{{nodeName}}" }
   ]
  },
  {
   "title": "CPU of Tasks",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "tasks_cpu_percentage{}", "legendFormat": "{{taskName}}" }
   ]
  },
  {
   "title": "Memory of Tasks",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "tasks_memory_percentage{}", "legendFormat": "{{taskName}}" }
   ]
  }
 ]
}